# Generated by Django 5.2.7 on 2025-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
