# Generated by Django 5.2.7 on 2025-11-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_item_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'أجهزة إلكترونية'), ('clothes', 'ملابس'), ('furniture', 'أثاث'), ('others', 'أخرى')], default='others', max_length=20),
        ),
    ]
